# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: TestSSH
  
steps:



- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
    sshKeySecureFile: 'id_rsa'
    sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQD0uVru0qonodQa0U7otYGAd0UEwGWO91YYmFsUcBsw8RdZPaja+kDd+7iHRMYwpKzKlUb9B7mZbxwK04uwZWYgGVdWyH9tzvE0QirQ9pssyxG931kEFlyaNER0FouzwCRmAUYGbQrxsQrMgz4tpt1PeK3dKJBMmUo5XUYPk4DHvBNIwB/aPaaAAfmQyfu8mZu/3zp1M+M6hHfAc7FPrm3H+lyTnIhxB+COSdGYrUYpv6V0r/ZN8+ad200raVNg2rgY8onx/WUS+SJqQCqfNr07KUZW0y67B6mr5p+G2YARrRhHYjLqCfxMbupDnxwSGewb4IkaWRlLmJF7+MLRsZKm58e63hNicPN08Ti9oP1D0tG4gjw5Zv9L29E3SnJW/09ZPsZiZHtAb8T62mXp4ZHhTD7GnfVjDLnisfX3h1O9YrajFjtQlRDAJnnqMycYYBTlatVNMC0x0CqREKK6e1Dqg6HLHZytUuJgd3kBzoCR9FoSWnd5F+PffXUlqKsaWhiEw+0xFuVjRG7JN1RBbhFEPFKrg5cfqnp258INRDOzj/WHJb9WmMMcdM0wDU7oqi78aek9B8SxeoXiWtURkUwG1Thvf12Q7gfKxMTkphF+A+iIRGV92shlmBQcXLQDKEzdUMhoxrc6/7b2+4S+WCekJCSuNKk5/+LP2PihNR08NQ== np@workmail.com'